spring:
  datasource:
    url: jdbc:mysql://mysql:3306/lane_assist?useSSL=false&serverTimezone=UTC
    username: root
    password: password

# Override inference service URL for Docker environment
inference:
  service:
    url: http://inference:8000

# Enable actuator health endpoint for Docker health checks
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always