server:
  port: 8090

lanes:
  useVision: false             # LiDAR-only (no OCR)
  ppm: 5.0                     # pixels-per-meter; used only when input is already an image
  minAreaFrac: 0.0015          # min contour area as fraction of H*W
  epsilonFrac: 0.012           # approxPolyDP fraction (shape simplification)
  roadOverlapMin: 0.65         # polygon must lie mostly on road mask
  kernel:
    lengthFrac: 0.08           # rotated dilation kernel length ≈ 6–10% of max(H,W)
    thickFrac: 0.02            # band thickness; may be overridden by lane width rule
  tophat:
    kernelPx: 21               # 17–31 typical (odd only)
  debugFrames: true            # enable /debug ZIP with masks & overlay

polygons:
  ppm: 5.0                     # Legacy setting (backward compatibility)
  defaultPpm: 5.0              # Default PPM for PNG-only processing
  minAreaFrac: 0.0015          # Minimum contour area as fraction of H*W
  epsilonFrac: 0.012           # ApproxPolyDP fraction for shape simplification
  roadOverlapMin: 0.65         # Polygon must lie mostly on road mask
  kernel:
    lengthFrac: 0.08           # Rotated dilation kernel length (6-10% of max dimension)
    thickFrac: 0.02            # Band thickness; may be overridden by lane width rule
  tophat:
    kernelPx: 21               # Top-hat kernel size (17-31 typical, odd only)
  segmentation:
    enabled: false             # Enable MaskRCNN segmentation fusion
    url: http://inference:8000/infer

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# MaskRCNN Inference Service Configuration
inference:
  service:
    url: http://localhost:8000