spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EMS?useSSL=false&serverTimezone=UTC
    username: root
    password: ""     # empty per requirement
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# Lane extraction tuning (can be changed without code)
lanes:
  minAreaFrac: 0.0015          # fraction of image area to keep a polygon
  epsilonFrac: 0.012           # poly simplify (smaller -> more points)
  laneWidthFrac: 0.015         # dilation kernel vs image size
  exportJson: true             # include polygons in overlay response (X-Polygons header)